// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnK-KGum4JAVFPD7IUkwLz2EtSut5dyTg',
    appId: '1:24667641321:web:3615a1ff8204b08aad6778',
    messagingSenderId: '24667641321',
    projectId: 'areis-f6ce6',
    authDomain: 'areis-f6ce6.firebaseapp.com',
    storageBucket: 'areis-f6ce6.appspot.com',
    measurementId: 'G-4C7CFVC9VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8bJ96u9CyEkUiFXVK_N1Q-zpcJyDcHps',
    appId: '1:24667641321:android:fddd5ca518ddf26fad6778',
    messagingSenderId: '24667641321',
    projectId: 'areis-f6ce6',
    storageBucket: 'areis-f6ce6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk3lirH6sNPTuIR7I3Rc2u_IHIVISbokA',
    appId: '1:24667641321:ios:f25c67bbdd0c1031ad6778',
    messagingSenderId: '24667641321',
    projectId: 'areis-f6ce6',
    storageBucket: 'areis-f6ce6.appspot.com',
    androidClientId: '24667641321-g7e842rlssogm7mcqtnrnbr79bt2d8aj.apps.googleusercontent.com',
    iosClientId: '24667641321-nj8lrp7d81v9boaqcpljkmech7nmdcpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskTracker',
  );
}
